color: blue
fieldLayouts:
  f997fbbd-3d0f-4ed7-adc1-ba30da763d82:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8145df63-d12f-47b2-be61-8cc8a8fd6849
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 838aabf9-a30e-4616-ad7c-b89fe15d7cae # Title (Anchor)
            handle: blockTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 758a3b32-9080-4bd9-bcf4-94125e1493a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d7250f9-a00c-4732-a743-b46bb5d11646 # CK Editor - Standard
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e28da65a-afdc-46d5-9836-5356db6ad43d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f936530d-29a5-4460-9ccd-b586bfb25329 # Call to actions
            handle: cta
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19e39354-0b95-4efe-b985-cce67beab385
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f1e5136-4dc7-4574-bb44-3bf0909e1518
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3857f4aa-a319-44ec-8b5e-d907d3d1bf31 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aa25d54-3048-44b1-a43e-60454557a95b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebeecdff-5e28-44c3-8233-ca59e850eb04
        userCondition: null
handle: callToAction
hasTitleField: false
icon: link
name: 'Call To Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
