columnSuffix: null
handle: ckEditorStandard
instructions: null
name: 'CK Editor - Standard'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 7d23b02c-ad1d-44a8-9751-35fbdcc38963 # Standard
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
