columnSuffix: null
handle: ckEditorTable
instructions: null
name: 'CK Editor - Table'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 5dbe5a67-b60b-4529-a095-facb9b24a39b # Table
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
